add single precision (float32) mode
siboehm/lleaves pull request #70
Opened 2024-01-27 14:50 UTC by zjzjwang

Closes #69 

mostly copy from [this branch](https://github.com/siboehm/lleaves/tree/vectorize)

2024-01-28 22:02 UTC, siboehm requested changes
This is great stuff! Thank you for implementing it, changes look good apart from some minor interface & variable naming issues.

2024-01-28 22:02 UTC, siboehm commented on tests/test_benchmark.py
> +    airline_X = df.to_numpy(np.float64)
Huh I never noticed that I was accidetnally running these with float32

2024-01-28 22:02 UTC, siboehm requested changes
This is great stuff! Thank you for implementing it, changes look good apart from some minor interface & variable naming issues.

2024-01-29 15:30 UTC, zjzjwang commented on lleaves/lleaves.py
> +    def __init__(self, model_file, dtype="float64"):
I originally thought the same, but seeing you put it in [`__init__`](https://github.com/siboehm/lleaves/blob/36677dde5116ddd9d4bf978b0506e7d8d7911a14/lleaves/lleaves.py#L46), I wrote it that way too.

2024-01-29 15:32 UTC, zjzjwang commented on lleaves/compiler/codegen/codegen.py
> +def get_fdtype(double_precision):
Changed to `use_fp64`.

2024-01-29 15:36 UTC, zjzjwang commented on lleaves/compiler/tree_compiler.py
> +    double_precision=True,
Sure.

2024-01-29 15:59 UTC, siboehm commented
LGTM, thanks for the PR @zjzjwang! Will try to do a release on the weekend

2024-01-29 16:01 UTC, merged